### ISSUE TITLE
Having trouble working the plugin

### ISSUE THREAD

**Issue by kenzo945** [NeonWizard/SCP-TranquilizerGun#7]
hi i have followed the instructions to install the mod placing the .dll into the sm_plugins folder however i dont believe the plugin is actually working despite the fact that i have another plugin installed that actually tells me which plugins are active on my server both this and item manager come up as active.

my main reason for beleiving that the plugin is not working is due to the fact that the imgive command keeps coming up as does not exit that and i cant find the tranqgun anywhere in game, ,y server is hosted on zap hosting so im not sure if perhaps that is the issue here but any help would be greatly appreciated

**Comment by wendihouse** [comment]
Hey, did you ever get this plugin to work?  I too have a server hosted on ZAP and just can’t get this to work.  I’m new to all this so it’s probably me that’s the problem!  I’ve uploaded the dll files in the correct place, but do I have to copy all the configs across too?  I’ve copied them into the gameplay txt , but when I use the imgive command, it’s not working.  I can’t even find the gun anywhere in game.  Any help you can give would be greatly appreciated.

**Comment by NeonWizard** [comment]
@wendihouse Sorry for the late response! This plugin is heavily outdated and most likely doesn't work with newer versions of SMOD. If there is a demand for it and I have time, I'll update the plugin, otherwise for now I'd suggest uninstalling it.

**Comment by NeonWizard** [comment]
Closed as this plugin is now deprecated.
