### ISSUE TITLE
IMGIVE command doesn't work

### ISSUE THREAD

**Issue by Hasherin** [NeonWizard/SCP-TranquilizerGun#8]
I tried to add the Tranq gun to myself but it said that it doesn't exist, but the gun can be found in SCP-096's chamber. I use the steam tool and MultiAdmin typed out 2 warnings:
[WARN] [xyz.wizardlywonders.TranquilizerGun] Trying to access a config setting that isn't registered to the plugin, this is bad practice.
[WARN] [DEFAULT_CONFIG_RESOLVER] Default setting for config SM_ENABLE_GHOSTMODE does not exist

**Comment by NeonWizard** [comment]
Closed as this plugin is now deprecated.
